- Pipfile
- Pipfile.lock
- src/api/models.py
- src/api/routes.py
- src/app.py
- src/front/js/pages/login.jsx
> Rutas login y sign up creadas con la seguridad implementada

- src/front/js/pages/login.jsx
- src/front/js/store/flux.js
se conecto el back con el front para obtener el token de inicio de sesion
> se unio el back y el front del login

- .vscode/settings.json
- package-lock.json
- package.json
- src/api/config.py
- src/api/routes.py
- src/api/utils.py
- src/app.py
> configuracion de cloudinary terminada Back End

- src/front/js/component/uploadToCloudinary.jsx
- src/front/js/pages/home.js
- src/front/js/store/flux.js
> cloudinary front end agregado, el flux configurado correctamente, y una vista de prueba para cargar archivos

- migrations/versions/566ab2aef2d5_.py
- src/api/routes.py
- src/front/styles/footer.css
se modifico endpoint de newsletter
> Footer frontend

- src/front/styles/Hero.css
- src/front/styles/Navbar.css
> hero terminado y funcional

- src/front/js/component/navbar.js
- src/front/js/layout.js
- src/front/js/pages/ContactUs.jsx
- src/front/styles/ContactUs.css
> se empezo a trabajar en vista contact us

- src/front/js/component/Aday.jsx
- src/front/js/pages/ContactUs.jsx
- src/front/js/pages/home.js
- src/front/styles/ContactUs.css
- src/front/styles/Hero.css
> A day section front end

- src/front/js/pages/Getintouch.jsx
- src/front/styles/Getintouch.css
> Programs backend

- package-lock.json
- src/front/js/pages/Events.jsx
- src/front/styles/Events.css
> modificacion en Events

- src/front/js/pages/Events.jsx
- src/front/styles/Events.css
> se agrego carrusel

- package-lock.json
- src/front/js/pages/Programs.jsx
> Carrusel programs frontend terminado

- src/front/js/pages/Programs.jsx
- src/front/js/store/flux.js
> Conexion frontend-backend programs terminada

- src/front/js/layout.js
- src/front/js/pages/ConfirmAttendance.jsx
- src/front/js/pages/Events.jsx
- src/front/js/pages/MoreInfo.jsx
- src/front/styles/ConfirmAttendance.css
> se creo vista de formulario confirm attendance

- src/front/js/layout.js
- src/front/js/pages/Allprograms.jsx
- src/front/js/pages/Programs.jsx
> Vista Allprograms terminada

- src/front/js/pages/Allprograms.jsx
- src/front/js/pages/Programs.jsx
> Modal connection with programs and Allprograms

- src/front/js/pages/Allprograms.jsx
Reverts 4GeeksAcademy/DaycareProyectoFinal#85
> Revert "allprograms update"

- src/api/models.py
- src/api/routes.py
- src/front/js/component/admin/ClassesView.jsx
- src/front/js/store/flux.js
back and front connection of dashboard admin classes
> Admin dashboard classes frontend

- src/front/js/component/Classes.jsx
- src/front/js/component/admin/ClassesView.jsx
> Card class home frontend

- src/api/routes.py
- src/front/js/component/admin/ClassesView.jsx
- src/front/js/component/admin/EventsView.jsx
- src/front/js/store/flux.js
> event view in the admin dashboard is finished ✅

- src/api/routes.py
- src/front/js/component/admin/ClassesView.jsx
- src/front/js/component/admin/EventsView.jsx
- src/front/js/pages/Events.jsx
- src/front/js/store/flux.js
> connection view events with admin dashboard

- src/front/js/component/admin/ScheduleManagement.jsx
> schedule functionality

- migrations/versions/380e2e490d11_.py
- src/api/admin.py
- src/api/models.py
- src/api/routes.py
- src/front/js/component/admin/Gallery.jsx
- src/front/js/layout.js
- src/front/js/pages/Gallery.jsx
- src/front/js/store/flux.js
- src/front/styles/Gallery.css
> connection gallery with view gallery of dashboard admin 

- src/api/routes.py
- src/front/js/component/parent/ParentChildren.jsx
- src/front/js/component/parent/ParentHeader.jsx
- src/front/js/component/parent/ParentSidebar.jsx
- src/front/js/store/flux.js
> Upgrade parent dashboard

- src/front/js/component/footer.js
- src/front/js/layout.js
- src/front/js/pages/home.js
> fixed footer

- migrations/versions/6e3115afe7e8_.py
- package-lock.json
- package.json
- src/api/models.py
- src/api/routes.py
- src/front/js/component/PayPalButton.jsx
- src/front/js/component/parent/ParentPayments.jsx
- src/front/js/pages/home.js
- src/front/js/store/flux.js
> Pay pal2.0

- src/api/models.py
- src/api/routes.py
- src/front/js/component/parent/ParentDashboard.jsx
- src/front/js/component/parent/ParentPayments.jsx
- src/front/js/component/parent/ParentSidebar.jsx
- src/front/js/component/parent/PaymentHistory.jsx
- src/front/js/layout.js
- src/front/js/store/flux.js
> Improvements in PayPal payment control, Payment history added to parent dashboard

- migrations/versions/fc43301dcf3f_.py
- src/api/routes.py
- src/front/js/component/teacher/TeacherOverview.jsx
- src/front/js/component/teacher/TeacherStudents.jsx
- src/front/js/store/flux.js
> Dashboard teacher 

- src/front/js/component/teacher/TeacherOverview.jsx
- src/front/js/component/teacher/TeacherSettings.jsx
- src/front/js/store/flux.js
> Dashboard teacher views update

- src/front/js/component/admin/EnrollmentsView.jsx
- src/front/js/component/parent/ParentActivities.jsx
- src/front/js/component/parent/ParentHeader.jsx
- src/front/js/component/parent/ParentSchedule.jsx
- src/front/js/component/parent/ParentVirtualClassesEnroll.jsx
> View schedule and activites 

- migrations/versions/6aaecffa0437_.py
- src/api/models.py
- src/api/routes.py
- src/front/js/component/teacher/TeacherHeader.jsx
- src/front/js/component/teacher/TeacherOverview.jsx
- src/front/js/component/teacher/TeacherSchedule.jsx
- src/front/js/store/flux.js
> Dashboard teacher config

- src/front/js/component/parent/ParentVirtualClasses.jsx
- src/front/js/layout.js
> fetch in parent virtual classes

- src/front/js/component/parent/parentMessages.jsx
> functionality mssage parents

- src/api/routes.py
Reverts 4GeeksAcademy/DaycareProyectoFinal#194
> Revert "v5"

- src/api/routes.py
Reverts 4GeeksAcademy/DaycareProyectoFinal#195
> Revert "Revert "v5""

- migrations/env.py
- migrations/versions/31e032b74160_.py
- src/front/js/layout.js
Reverts 4GeeksAcademy/DaycareProyectoFinal#192
> Revert "Css update"
